project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
preserve_hierarchy: 1
files:
  - source: /app/public/locales/fr/*.json
    translation: /app/locales/%two_letters_code%/%original_file_name%
