export enum ActionType {
  GET_CARD_IN_DECK_OR_DEFAUSSE = 'GET_CARD_IN_DECK_OR_DEFAUSSE',
  SWITCH_WITH_DEFAUSSE = 'SWITCH_WITH_DEFAUSSE',
  SWITCH_WITH_DECK = 'SWITCH_WITH_DECK',
  INTERVENTION = 'INTERVENTION',

  VISION = 'VISION',
  SWITCH = 'SWITCH',
  BLOCKER = 'BLOCKER',
  MIX_MAIN = 'MIX_MAIN',
}
